overrides:
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  node-forge@<1.3.2: '>=1.3.2'
  on-headers@<1.1.0: '>=1.1.0'
  qs@<6.14.1: '>=6.14.1'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
